i=imread("C:\Users\K.Ramya\Downloads\vib25 b2 c.png");
imshow(i)
%%
grayi=im2gray(i);
imshow(i)
%%

%%
adji=imadjust(grayi);
imshow(grayi)
%%
bwt=segmentImage(adji);
imshow(bwt)

%%
props=regionprops("table",bwt,"Area");
areaOfImage=12*12
areapixels=sum(props.Area)
areaofwhiteincm=areapixels*((10/350)^2)
voidsArea=  -areaofwhiteincm+(10*10)
%%

%%


%%
function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Nov-2022
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Threshold image - manual threshold
BW = X > 88;

% Close mask with disk
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end